//
//  TLWatchView.h
//  TexLege
//
//  Created by Greg Combs on 8/25/14.
//  Copyright (c) 2014 Gregory S Combs. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface TLWatchView : NSObject

// iOS Controls Customization Outlets
@property(retain, nonatomic) IBOutletCollection(NSObject) NSArray* normalCanvasTargets;
@property(retain, nonatomic) IBOutletCollection(NSObject) NSArray* selectedCanvasTargets;

// Colors
+ (UIColor*)ovalNormalColor;
+ (UIColor*)starNormalColor;
+ (UIColor*)ovalSelectedColor;
+ (UIColor*)starSelectedColor;

// Drawing Methods
+ (void)drawNormalCanvasWithFrame: (CGRect)frame;
+ (void)drawSelectedCanvasWithFrame: (CGRect)frame;

// Generated Images
+ (UIImage*)imageOfNormalCanvasWithFrame: (CGRect)frame;
+ (UIImage*)imageOfSelectedCanvasWithFrame: (CGRect)frame;

@end
